#
# "main" pseudo-component makefile.
#
# (Uses default behaviour of compiling all source files in directory, adding 'include' to include path.)

ifdef CONFIG_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT
CPPFLAGS += -DOPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT=$(CONFIG_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT)
endif

ifdef CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT
CPPFLAGS += -DOPENTHREAD_CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT=$(CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT)
endif

ifdef CONFIG_PLATOFRM_ENABLE_SLEEP
CPPFLAGS += -DCONFIG_PLATOFRM_ENABLE_SLEEP=$(CONFIG_PLATOFRM_ENABLE_SLEEP)
endif


COMPONENT_ADD_INCLUDEDIRS += Include
