#!/bin/sh
# /***************************************************************************
# *               ZBOSS Zigbee 3.0                                           *
# *                                                                          *
# *  This is unpublished proprietary source code of DSR Corporation          *
# *  The copyright notice does not evidence any actual or intended           *
# *  publication of such source code.                                        *
# *                                                                          *
# *          Copyright (c) 2012-2018 DSR Corporation, Denver CO, USA.        *
# * http://www.dsr-zboss.com                                                 *
# * http://www.dsr-corporation.com                                           *
# *                                                                          *
# *                            All rights reserved.                          *
# *                                                                          *
# *                                                                          *
# * ZBOSS is a registered trademark of Data Storage Research LLC d/b/a DSR   *
# * Corporation                                                              *
# *                                                                          *
# ****************************************************************************
# PURPOSE: 
# */
killall network_simulator
rm -f /tmp/*.write
rm -f /tmp/*.read
make clean
rm -f *.log *.dump *.pcap ns.txt *.*~ *.nvram *.map *.pdml
